
services:
  app:
    build: .
    container_name: calculadora-app
    ports:
      - "3000:3000"

    command: npm start

  test:
    build: .
    container_name: calculadora-test
    command: npm test
